import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

export type InvoicePdfData = {
  invoiceNumber: string;
  companyName: string;
  customerName: string;
  customerEmail: string | null;
  billingAddress: string | null;
  issuedAt: string;
  dueAt: string | null;
  notes: string | null;
  lineItems: { description: string; amount: number }[];
};

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica" },
  header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 24 },
  title: { fontSize: 20, fontWeight: 700 },
  label: { color: "#64748b", fontSize: 9, textTransform: "uppercase", marginBottom: 2 },
  block: { marginBottom: 16 },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: "#e2e8f0" },
  headerRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: "#0f172a", fontWeight: 700 },
  totalRow: { flexDirection: "row", justifyContent: "space-between", paddingTop: 10, marginTop: 4, fontSize: 13, fontWeight: 700 },
  desc: { flex: 1 },
  amount: { width: 80, textAlign: "right" },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 9, color: "#94a3b8" },
});

/**
 * Every field here is real data passed in — no placeholder Latin text
 * or "Sample Company" left in like a template. Not a legally-formatted
 * invoice template (no tax lines, no jurisdiction-specific requirements)
 * — a clean, correct proof-of-billing document, same honesty as the
 * delivery signature capture's own "not a legally binding e-signature
 * service" disclaimer elsewhere in this app.
 */
export function InvoicePdfDocument({ data }: { data: InvoicePdfData }) {
  const total = data.lineItems.reduce((sum, li) => sum + li.amount, 0);

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.title}>Invoice {data.invoiceNumber}</Text>
            <Text style={{ marginTop: 4, color: "#64748b" }}>{data.companyName}</Text>
          </View>
          <View>
            <Text style={styles.label}>Issued</Text>
            <Text>{data.issuedAt}</Text>
            {data.dueAt && (
              <>
                <Text style={{ ...styles.label, marginTop: 8 }}>Due</Text>
                <Text>{data.dueAt}</Text>
              </>
            )}
          </View>
        </View>

        <View style={styles.block}>
          <Text style={styles.label}>Bill to</Text>
          <Text>{data.customerName}</Text>
          {data.customerEmail && <Text>{data.customerEmail}</Text>}
          {data.billingAddress && <Text>{data.billingAddress}</Text>}
        </View>

        <View style={styles.headerRow}>
          <Text style={styles.desc}>Description</Text>
          <Text style={styles.amount}>Amount</Text>
        </View>
        {data.lineItems.map((li, i) => (
          <View style={styles.row} key={i}>
            <Text style={styles.desc}>{li.description}</Text>
            <Text style={styles.amount}>${li.amount.toFixed(2)}</Text>
          </View>
        ))}
        <View style={styles.totalRow}>
          <Text>Total</Text>
          <Text>${total.toFixed(2)}</Text>
        </View>

        {data.notes && (
          <View style={{ ...styles.block, marginTop: 24 }}>
            <Text style={styles.label}>Notes</Text>
            <Text>{data.notes}</Text>
          </View>
        )}

        <Text style={styles.footer}>Generated by Corridor Freight.</Text>
      </Page>
    </Document>
  );
}
