import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

export type SettlementPdfData = {
  companyName: string;
  driverName: string;
  createdAt: string;
  paidAt: string | null;
  notes: string | null;
  lineItems: { line_type: string; description: string; amount: number }[];
};

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica" },
  header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 24 },
  title: { fontSize: 20, fontWeight: 700 },
  label: { color: "#64748b", fontSize: 9, textTransform: "uppercase", marginBottom: 2 },
  block: { marginBottom: 16 },
  sectionLabel: { fontSize: 10, fontWeight: 700, marginTop: 12, marginBottom: 4, textTransform: "uppercase", color: "#64748b" },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: "#e2e8f0" },
  totalRow: { flexDirection: "row", justifyContent: "space-between", paddingTop: 10, marginTop: 4, fontSize: 13, fontWeight: 700 },
  desc: { flex: 1 },
  amount: { width: 80, textAlign: "right" },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 9, color: "#94a3b8" },
});

const SECTION_LABELS: Record<string, string> = {
  load_pay: "Load pay",
  reimbursement: "Reimbursements",
  deduction: "Deductions",
  advance_repayment: "Advance repayments",
};

/**
 * Same proof-of-record honesty as InvoicePdfDocument's own comment —
 * real numbers only, no template placeholder text. Not a paystub in
 * the payroll-tax-withholding sense (no W-2/1099 tax fields) — a
 * settlement statement documenting the pay math, same as this app's
 * settlement itself is a proof-of-payout record, not a tax document.
 */
export function SettlementPdfDocument({ data }: { data: SettlementPdfData }) {
  const net = data.lineItems.reduce((sum, li) => {
    const signed =
      li.line_type === "deduction" || li.line_type === "advance_repayment" ? -li.amount : li.amount;
    return sum + signed;
  }, 0);

  const groups: { type: string; items: typeof data.lineItems }[] = ["load_pay", "reimbursement", "deduction", "advance_repayment"]
    .map((type) => ({ type, items: data.lineItems.filter((li) => li.line_type === type) }))
    .filter((g) => g.items.length > 0);

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.title}>Settlement statement</Text>
            <Text style={{ marginTop: 4, color: "#64748b" }}>{data.companyName}</Text>
          </View>
          <View>
            <Text style={styles.label}>Driver</Text>
            <Text>{data.driverName}</Text>
            <Text style={{ ...styles.label, marginTop: 8 }}>Created</Text>
            <Text>{data.createdAt}</Text>
            {data.paidAt && (
              <>
                <Text style={{ ...styles.label, marginTop: 8 }}>Paid</Text>
                <Text>{data.paidAt}</Text>
              </>
            )}
          </View>
        </View>

        {groups.map((group) => (
          <View key={group.type} style={styles.block}>
            <Text style={styles.sectionLabel}>{SECTION_LABELS[group.type]}</Text>
            {group.items.map((li, i) => (
              <View style={styles.row} key={i}>
                <Text style={styles.desc}>{li.description}</Text>
                <Text style={styles.amount}>
                  {group.type === "deduction" || group.type === "advance_repayment" ? "-" : ""}$
                  {li.amount.toFixed(2)}
                </Text>
              </View>
            ))}
          </View>
        ))}

        <View style={styles.totalRow}>
          <Text>Net pay</Text>
          <Text>${net.toFixed(2)}</Text>
        </View>

        {data.notes && (
          <View style={{ ...styles.block, marginTop: 24 }}>
            <Text style={styles.label}>Notes</Text>
            <Text>{data.notes}</Text>
          </View>
        )}

        <Text style={styles.footer}>Generated by Corridor Freight.</Text>
      </Page>
    </Document>
  );
}
